### ISSUE TITLE
Create static pages

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction-swag-shop#11]
### Static pages

**Story**
As a user I want to browse content that's not directly related to buying products. That could be terms & conditions, about pages, general information, a blog post, you name it.  This user story covers approximately up to 10 static pages. 

**Acceptance criteria**
- For each static page, there needs to be a a link into it. Usually this will be the footer.
- Static pages should be available in different languages, depending on which language is selected

**Questions**
- Assumption was, that there's no CMS involved for static pages. **Not sure, this holds true, though ...**

**Comment by rymorgan** [comment]
@prinzdezibel 
<img width="1198" alt="swag-store" src="https://user-images.githubusercontent.com/20409254/35169767-a5e82d28-fd12-11e7-9140-3d238b90d647.png">

**Comment by sophiehe** [comment]
Copy: 

'your everyday essentials.' to 'Your everyday essentials.'
'Lorem ipsum...' to 'Shop your favorites on our Instagram feed.'


GET A DEMO --- where is this field going to? 

'Create a premiere ecommerce experience...' to 'Want to see what you can do with Reaction? Submit your email.'

**Comment by prinzdezibel** [comment]
@sophiehe Re: GET A DEMO:   Right now nothing happens. The form collects the email and displays a success message, event though it's a no-op. I would need to know what exactly should happen. Easiest thing would be to send an email to a predefined address with a predefined text.

**Comment by sophiehe** [comment]
@rymorgan @prinzdezibel so maybe we should remove the email field and instead include a CTA button that leads to a pop-up form, eg.: 

'Want to see what you can do with Reaction?' 
CTA: Get a demo

**Comment by rymorgan** [comment]
Yea, the swag shop is both a demo of a reaction shop and an advertising tool for us :)

**Comment by sophiehe** [comment]
Hm.. so maybe we should send them to the GitHub repo, so they can get started?

**Comment by sophiehe** [comment]
Or, we could have them sign up for our email newsletter.

<img width="467" alt="screen shot 2018-01-22 at 11 01 08 am" src="https://user-images.githubusercontent.com/20484811/35238959-f3a01244-ff63-11e7-9fd6-20614c422daa.png">

**Comment by rymorgan** [comment]
I think the swag shop is an opportunity to get more people into the top of the funnel. @cindyfirestone Thoughts? Should we have a link to 'get a demo' on the swag shop? That would be like the one on the site.

**Comment by sophiehe** [comment]
IMO, I don't know if that makes the most sense. As you mentioned, the swag shop IS a demo, so they've kind of already gotten their demo, right?

**Comment by rymorgan** [comment]
They've only gotta a demo of the front end, not the admin tool or the Reaction ecosystem.

**Comment by cindyfirestone** [comment]
Will this swag shop replace the current https://swag.getreaction.io/? 

I do think it's a good idea for us to capture the information of people who hit this site, maybe not `get a demo` but `get more information` instead

**Comment by prinzdezibel** [comment]
@cindyfirestone 

> Will this swag shop replace the current https://swag.getreaction.io/?

Yes.

**Comment by cindyfirestone** [comment]
@prinzdezibel got it thanks, in that case it get a demo doesn't make sense because I'm assuming the login info will be on there where they can test the admin functionality.

**Comment by zenweasel** [comment]
I still think we are missing out if we don't have some CTA to get them into the top of the sales funnel?

**Comment by rymorgan** [comment]
@zenweasel Totally agree. I don't' know why we wouldn't try to funnel them somewhere. If they're here, then they're evaluating our offering.

**Comment by cindyfirestone** [comment]
@zenweasel @rymorgan I don't disagree, my comment above mentioned a `get more info` form instead of `get a demo`

**Comment by zenweasel** [comment]
So just to clear up some confusion which is probably my fault. There will be two "swag shops":
One will be the “demo site” where they will be able to login, and one will be the actual swag shop where we sell stuff where they will not be able login as an admin.

They will look mostly the same, but one will actually take your money and send you junk

**Comment by zenweasel** [comment]
@cindyfirestone @rymorgan So then is there a "Get More Info" form in the design? If not can we add it or can @prinzdezibel just add it? It can just send stuff to Intercom like the main site does? Hopefully that won't generate too much junk for sales.

**Comment by cindyfirestone** [comment]
@zenweasel in that case, it would make sense for us to keep `get a demo` on this new swag shop since they're not seeing anything beyond the custom design and checkout process. The form should be the same as the form on the main reaction site --although we've revamped the fields and need to run it past Sara first before making the update.

**Comment by sophiehe** [comment]
Thanks for the clarification, @zenweasel. How about this copy then:

'Reaction Commerce' to 'Built on Reaction Commerce'
'Feeling inspired? See what you can do with our open source platform." 
CTA: Get a demo

**Comment by prinzdezibel** [comment]
@sophiehe will change the text to your proposal
@rymorgan Can you provide me the design for the form?
@cindyfirestone Please let me know the revamped fields after talking to Sara

**Comment by rymorgan** [comment]
@prinzdezibel The form design can match the one on the site. (Wait until the fields are updated).
