### ISSUE TITLE
Tag/category tiles (user)

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction-swag-shop#12]
## Landing page should feature an area with image tiles for each product category.

**Story**
As an user – when entering the shop – I want to get a quick overview what product categories are available. This allows me to quickly find the product I'm interested in.

**Acceptance criteria**
- Given that there's a navigation tag called `MEN` there will be a corresponding category tile that displays an image that represents the category `MEN`. 
- The image tile is clickable. When clicking it, the user navigates away from current page to a new page "Cat Grid" (https://github.com/reactioncommerce/reaction-swag-shop/issues/6)
- When navigating into a image tile, the resulting "Cat Grid" view shows only products that have the pertinent top-level tag assigned (e.g.: MEN). 
- The behaviour of clicking an image tile is indifferent of clicking the corresponding tag link in the navigation bar.

**Questions & Remarks**
- The categories could correlate to product hashtags
- Categories (hashtags) needs to be linked to images somehow. The easiest (, but most inflexible) way would be to hardcode this in page template.
- For small screens, not all categories would be displayed. Are the hidden categories invariant?

**Comment by prinzdezibel** [comment]
@zenweasel My understanding is, that we still need this functionality for phase1, but not dynamically available in admin backend. I'm asking, because it's labeled `phase2` right now.

**Comment by zenweasel** [comment]
Yes, but should we rewrite the ticket to reflect the actual functionality?

**Comment by prinzdezibel** [comment]
We decided to postpone the full fledged functionality that would allow the admin to specify a header image in the backend and possibly also set some display options how to show it on the landing page.

For version 1, a simple hard-coded solution should suffice.

**Comment by rymorgan** [comment]
@prinzdezibel The sketch file that's plugged into Zeplin wasn't configured right. It is now, so you should access to the category asset in Zeplin. Let me know if there are other images you need. 

https://zoom.us/j/426594362

**Comment by prinzdezibel** [comment]
@rymorgan Thank you! That works and helps me a lot already. But one thing that could be better (although I don't know if Sketch/Zeplin supports that): The images contain button elements and font types which is not suitable for direct consumption.

Is there anything you can do about that?

![home_desk_-_website_-_zeplin_and_reactioncommerce_reaction_-_gitter](https://user-images.githubusercontent.com/1733229/34709580-16851c2e-f518-11e7-8e7c-603ab9bf85d0.jpg)

**Comment by rymorgan** [comment]
@prinzdezibel Not that I can figure out, sort of lame. The agency that designed this made the file a little weird. Here's a zip. 
[category-image-assets.zip](https://github.com/reactioncommerce/reaction-swag-shop/files/1616252/category-image-assets.zip)
