### ISSUE TITLE
Landing Page: Responsive image gallery

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction-swag-shop#14]
## Responsive image gallery
**Story**
As an user, I should see a tiled section with different images (could be linked to an URL) above the footer. These tiles will serve as possibility to provide secondary information in a visually attractive way.

**Acceptance criteria**
- Some images may link to other URLs. When clicking on a clickable URL, the user navigates away from current page.
- Depending on the screen estate, the pictures with no user-interaction (no linked URLs) are shrinking more than others. **(Assumption should be re-affirmed through design office).**

### Questions
- Should these images be static/invariant? Or do they need to be maintainable through admin backend?

**Comment by prinzdezibel** [comment]
@zenweasel My understanding is, that this feature is still needed - even for phase 1 - but only as one-off solution in a hard-coded manner.  So I'm not sure why this story is marked as 'phase2'

**Comment by zenweasel** [comment]
Yes, you're right. The "content-editor" portion is phase2 but we still need the images, etc.

**Comment by prinzdezibel** [comment]
@rymorgan Could you export me the images from Sketch and send it to me? Thank you.

**Comment by rymorgan** [comment]
@prinzdezibel These images are pulled from Reaction's instagram. I believe the idea here was to show a feed of the latest Instagram images. Not sure if that's worth spending our time on but... https://www.instagram.com/reactioncommerce/
