### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction-swag-shop#25]
Doc just says this updates demo.reactioncommerce.com, which is not responding. 

This is being deployed on `https://swag.getreaction.io/`  (should we / are we going to run this on demo)?

**Comment by prinzdezibel** [comment]
@aaronjudd There's a pull request addressing this issue: https://github.com/reactioncommerce/reaction-swag-shop/pull/22

(I did not realize it's not merged yet , when talking about in community call)

**Comment by prinzdezibel** [comment]
Issue #25 fixed via #22.
