### ISSUE TITLE
Keep getting the Error: Unknown asset: plugins/reaction-swag-shop/images/BCTMZ6HTxFSppJESk.jpg

### ISSUE THREAD

**Issue by vineethEPM** [reactioncommerce/reaction-swag-shop#39]
I followed the exact same steps mentioned in README, but when I run reaction command, i keep getting following error:

Error: Unknown asset: plugins/reaction-swag-shop/images/BCTMZ6HTxFSppJESk.jpg
    at getAsset (/Users/vineeth/Projects/epm/.meteor/local/build/programs/server/boot.js:328:19)
    at Object.getBinary (/Users/vineeth/Projects/epm/.meteor/local/build/programs/server/boot.js:342:16)
    at Object.methods.importProductImages (imports/plugins/custom/reaction-swag-shop/server/methods.js:128:31)

<img width="1251" alt="screen shot 2018-01-26 at 3 24 33 pm" src="https://user-images.githubusercontent.com/35692006/35434415-10293afc-02ad-11e8-9d8e-59a8e2882648.png">

**Comment by prinzdezibel** [comment]
@vineethEPM  This happens when the default data fixture was loaded. Please do
`reaction reset -n` and ensure that the env variable SKIP_FIXTURES is set to 1 before running reaction.

**Comment by zenweasel** [comment]
@vineethEPM Make sure you are running reaction with `SKIP_FIXTURES=true reaction`. Otherwise it will load the default product and look for a image for it, which doesn't exist.

**Comment by vineethEPM** [comment]
@prinzdezibel : Thanks, It worked now.
