### ISSUE TITLE
"Error: Unknown asset:" even though env is set as suggested

### ISSUE THREAD

**Issue by bebob1** [reactioncommerce/reaction-swag-shop#45]
Hey there.

I set up a fresh reaction and a fresh instance of the swag shop plugin.

My pictures are in this directory: "imports/plugins/custom/reaction-swag-shop/images/"

I am 100% sure the path is correct.

On startup (_export SKIP_FIXTURES=1 && reaction_) everything look fine first but then ends in 

> Error: Unknown asset: imports/plugins/custom/reaction-swag-shop/images/h2v7MYCXBtjMm7Piv.jpg

The product ID comes out of the plugin data of reaction-swag-shop, which leads me to believe the setting of the ENV variable SKIP_FIXTURES is working well. Otherwise Reaction would try to load a picture with the name of "BCTMZ6HTxFSppJESk.jpg" as this is the first product of the default fixures.

I ran out of clues. Am I the only one with this problem or is this a bug?

Regards
bebob

**Comment by prinzdezibel** [comment]
@bebob1 Please make sure to do a `reaction reset -n ` now to reset the database.

 If this error happens, you've accidentally loaded the default data fixtures. This happens if you are running reaction (maybe the first time) without having `SKIP_FIXTURES` set.

**Comment by prinzdezibel** [comment]
@bebob1 Also make sure you really have the latest reaction-cli downloaded.
```
$ reaction -v 
``` 
should output 
```
Reaction CLI: 0.26.4
```

**Comment by jshimko** [comment]
FYI, 0.27.0 is the current latest `reaction-cli` version.

**Comment by prinzdezibel** [comment]
Thank you, @jshimko!  It should read: `should output 0.26.4 or newer`

**Comment by bebob1** [comment]
I updated to the latest reaction-cli and it works now :)

Thanks for your help!
