### ISSUE TITLE
All accounts are published once you log in

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-swag-shop#55]
## Problem
When I go to https://swag.getreaction.io/ and log in with the default admin credentials, the browser subscribes to all 4300+ account records.

## Reproduce
1. Go to https://swag.getreaction.io/ and log in with the default admin credentials
1. Notice there is some lag in signing in. Enter `ReactionCore.Collections.Accounts.find().count()` in console.

## Solution
I didn't investigate, but my guess is that the reset script is using the same value for some field for all accounts, and that value is used in the accounts publication selector.

**Comment by zenweasel** [comment]
Issue moved to [reactioncommerce/reaction-demo #3](https://github.com/reactioncommerce/reaction-demo/issues/3) via [**ZenHub**](https://www.zenhub.com/)
