### ISSUE TITLE
Unknown asset issue running docker-compose

### ISSUE THREAD

**Issue by jason-magnetic-io** [reactioncommerce/reaction-swag-shop#56]
What is the correct way to fix the `Unknown asset: plugins/reaction-swag-shop/images/BCTMZ6HTxFSppJESk.jpg` issue when running the store using docker-compose?

I've created a customer docker image with the swag-shop. Setting `SKIP_FIXTURES=1` works when running `reaction` locally but how do I fix it if I'm running the store as a docker container?

**Comment by prinzdezibel** [comment]
Define SKIP_FIXTURES as environment variable in your docker-compose.yml.

**Comment by pvgupta24** [comment]
@prinzdezibel , even though SKIP_FIXTURES environment variable is set to 1, it shows the same unknown asset error for me while running in in docker. (with reaction 2.0)
