### ISSUE TITLE
Add to cart button always adds one item regardless of user input.

### ISSUE THREAD

**Issue by cyber-claws** [reactioncommerce/reaction-swag-shop#57]
##  Expected behavior
When you increase the number of items to add the cart on the pdp page and you click **add to cart**, that number of products must be added to cart/

## Actual behavior
**add to cart** button always adds one item to cart at the time, regardless of the use number input.

## Steps to reproduce the behavior
- On the pdp increase the number of items to add to cart next to the add to cart button.
- Click add to cart.
- Check number of items in cart.

**Comment by MWPAWAR** [comment]
I also faced same issue after adding multiple items to cart.

**Comment by cyber-claws** [comment]
## A workaround

in `import/plugins/custom/reaction-swag-shop/clients/components/product-detail-simple/addToCartButton.js` in the function `add()` add a callback to the `setState()` function like so:

```js
 add = (value) => {
    this.setState((prev) => {
      if (prev.value === 1 && value < 0) {
        return {
          value: 1
        };
      }
      return {
        value: prev.value + value
      };
    }, () => this.props.onCartQuantityChange(null, this.state.value) );
 };
```
