### ISSUE TITLE
Update to make compatible with Reaction v1.11.0

### ISSUE THREAD

**Issue by Akarshit** [reactioncommerce/reaction-swag-shop#61]

**Comment by nicroto** [comment]
Is the project at all runnable under 1.11.0?

The error I get (upon running `export SKIP_FIXTURES=1 && reaction`) is:

```
Error: Cannot find module '../../../../../core/collections'
    at makeMissingError (packages/modules-runtime.js:231:12)
    at require (packages/modules-runtime.js:241:19)
    at tags.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/tags.js:1:29)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/index.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/reaction-swag-shop/server/index.js:1:14)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at plugins.js (server/plugins.js:1:3419)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /Users/tsenkov/repos/example-store/.meteor/local/build/programs/server/app/app.js:110231:1
    at /Users/tsenkov/repos/example-store/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /Users/tsenkov/repos/example-store/.meteor/local/build/programs/server/boot.js:220:19
    at /Users/tsenkov/repos/example-store/.meteor/local/build/programs/server/boot.js:471:5
    at Function.run (/Users/tsenkov/repos/example-store/.meteor/local/build/programs/server/profile.js:510:12)
    at /Users/tsenkov/repos/example-store/.meteor/local/build/programs/server/boot.js:470:11
```

**Comment by Akarshit** [comment]
@nicroto Not right now. But this project will be updated soon(in a couple of days.)

**Comment by duyanhv** [comment]
this is the whole error in terminal
`reaction_1   | /home/node/.meteor/packages/meteor-tool/.1.6.1_1.164hzk5.nrx7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
reaction_1   | 						throw(ex);
reaction_1   | 						^
reaction_1   | 
reaction_1   | Error: Cannot find module '../../../../../core/collections'
reaction_1   |     at makeMissingError (packages/modules-runtime.js:231:12)
reaction_1   |     at require (packages/modules-runtime.js:241:19)
reaction_1   |     at tags.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/tags.js:1:29)
reaction_1   |     at fileEvaluate (packages/modules-runtime.js:343:9)
reaction_1   |     at require (packages/modules-runtime.js:238:16)
reaction_1   |     at index.js (imports/plugins/custom/reaction-swag-shop/lib/collections/schemas/index.js:1:14)
reaction_1   |     at fileEvaluate (packages/modules-runtime.js:343:9)
reaction_1   |     at require (packages/modules-runtime.js:238:16)
reaction_1   |     at index.js (imports/plugins/custom/reaction-swag-shop/server/index.js:1:14)
reaction_1   |     at fileEvaluate (packages/modules-runtime.js:343:9)
reaction_1   |     at require (packages/modules-runtime.js:238:16)
reaction_1   |     at plugins.js (server/plugins.js:1:3419)
reaction_1   |     at fileEvaluate (packages/modules-runtime.js:343:9)
reaction_1   |     at require (packages/modules-runtime.js:238:16)
reaction_1   |     at /opt/reaction/src/.meteor/local/build/programs/server/app/app.js:110393:1
reaction_1   |     at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:411:36
reaction_1   |     at Array.forEach (<anonymous>)
reaction_1   |     at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:220:19
reaction_1   |     at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:471:5
reaction_1   |     at Function.run (/opt/reaction/src/.meteor/local/build/programs/server/profile.js:510:12)
reaction_1   |     at /opt/reaction/src/.meteor/local/build/programs/server/boot.js:470:11
reaction_1   | => Exited with code: 1`
thanks in advanced

**Comment by Akarshit** [comment]
@duyanhv There is a PR already made to fix this. Just waiting for that to get merged.

**Comment by mikepuglisi** [comment]
Just learned about this problem the hard way...since the docs make no mention of the limitation. 

Waiting for merge as well.

**Comment by thegtagamer** [comment]
@Akarshit Bhai....its not working properly with the latest Reaction version The products are not getting loaded.

**Comment by hanselke** [comment]
any progress with this?
