### ISSUE TITLE
Errors Less Files

### ISSUE THREAD

**Issue by stunjiturner** [reactioncommerce/reaction-swag-shop#65]
=> Started proxy.                             
app/client/plugins.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
=> Errors prevented startup:                  
   
   While processing files with less (for target web.browser):
   reaction-swag-shop/client/styles/classes/footer.less:22:34: variable @screen-xs-max is undefined
   reaction-swag-shop/client/styles/classes/header.less:58:12: variable @navHeight is undefined
   reaction-swag-shop/client/styles/classes/landing.less:30:7: variable @mobile is undefined
   reaction-swag-shop/client/styles/classes/header.less:262:32: variable @screen-xs-max is undefined
   
=> Your application has errors. Waiting for file change.
=> A patch (Meteor 1.6.1.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.

**Comment by willmoss1000** [comment]
@stunjiturner do you not see these .less errors anymore?
