### ISSUE TITLE
Error on startup - "While processing files with ecmascript" 

### ISSUE THREAD

**Issue by xtebs** [reactioncommerce/reaction-swag-shop#67]
1 - Fresh (and working) installation of reaction.
2- Cloned reaction-swag-shop git to inside /imports/plugins/custom/
3 - ERROR: 
>Errors prevented startup:
> 
>    **While processing files with ecmascript (for target web.browser):**
> ***
> ***
> The new decorators proposal is not supported yet. You must pass the `"**decoratorsLegacy**": true`
>    option to @babel/preset-stage-2

Is babel7  incompatible with current reaction-swag-shop?

I tried dozens of solutions, no success.  
My package.json has already "decoratorsLegacy": true" on babel plugin description. 

reaction versions:
` reaction -v

Node: 8.11.3
NPM: 5.6.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.13.1
Reaction branch: master`

**Comment by xtebs** [comment]
Solved it. its a Babel version problem, solved by the PR "fix-ajporlante-1-13-0-compatibility". 
Waiting for the merge, or ( for those in a rush like myself :) ) solved it by cloning the branch directly. 
`git clone -b fix-ajporlante-1-13-0-compatibility https://github.com/reactioncommerce/reaction-swag-shop.git`

**Comment by zenweasel** [comment]
@xtebs Thanks. We'll try to get this merged today
